// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqHQZgQTrp7i_hSv3V1_MlO7ZIKuTtRQ',
    appId: '1:849322380987:web:632e28c146ba71a909e39e',
    messagingSenderId: '849322380987',
    projectId: 'math-fa2e3',
    authDomain: 'math-fa2e3.firebaseapp.com',
    storageBucket: 'math-fa2e3.appspot.com',
    measurementId: 'G-0P7HYTEHEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-Sl3ut1IBqzurZCVaZmIR7Ra2QvLjwI',
    appId: '1:849322380987:android:1f038676e917760909e39e',
    messagingSenderId: '849322380987',
    projectId: 'math-fa2e3',
    storageBucket: 'math-fa2e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOR9ZQXvgciI5urUUfQifsy5MJjbD5lD4',
    appId: '1:849322380987:ios:7257b9dee53f344409e39e',
    messagingSenderId: '849322380987',
    projectId: 'math-fa2e3',
    storageBucket: 'math-fa2e3.appspot.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOR9ZQXvgciI5urUUfQifsy5MJjbD5lD4',
    appId: '1:849322380987:ios:c0ba11b456e792e209e39e',
    messagingSenderId: '849322380987',
    projectId: 'math-fa2e3',
    storageBucket: 'math-fa2e3.appspot.com',
    iosBundleId: 'com.example.math.RunnerTests',
  );
}
